<html>
<head>
<title>Exception Handling in Python</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">Python中的异常处理</h1>
<blockquote>原文：<a href="https://levelup.gitconnected.com/exception-handling-in-python-1d685b29129c?source=collection_archive---------11-----------------------#2020-03-08">https://levelup.gitconnected.com/exception-handling-in-python-1d685b29129c?source=collection_archive---------11-----------------------#2020-03-08</a></blockquote><div><div class="fc ih ii ij ik il"/><div class="im in io ip iq"><div class=""/><div class=""><h2 id="03d8" class="pw-subtitle-paragraph jq is it bd b jr js jt ju jv jw jx jy jz ka kb kc kd ke kf kg kh dk translated">python中异常处理的简单解释</h2></div><p id="5ea5" class="pw-post-body-paragraph ki kj it kk b kl km ju kn ko kp jx kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">在本文中，我们将了解:</p><ul class=""><li id="d0e5" class="le lf it kk b kl km ko kp kr lg kv lh kz li ld lj lk ll lm bi translated">什么是异常，如何在python中处理异常？</li><li id="d594" class="le lf it kk b kl ln ko lo kr lp kv lq kz lr ld lj lk ll lm bi translated">如何处理多个内置异常？</li><li id="a305" class="le lf it kk b kl ln ko lo kr lp kv lq kz lr ld lj lk ll lm bi translated">如何创建自定义异常？</li></ul><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div class="gh gi ls"><img src="../Images/e5c1595371a04c80f74e137af22f0e94.png" data-original-src="https://miro.medium.com/v2/resize:fit:996/format:webp/1*Rul4eYuJiuGykgTbIWfFFg.png"/></div><figcaption class="ma mb gj gh gi mc md bd b be z dk translated">简·根格在<a class="ae me" href="https://unsplash.com/s/photos/exceptions?utm_source=unsplash&amp;utm_medium=referral&amp;utm_content=creditCopyText" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>上的照片</figcaption></figure><p id="dc97" class="pw-post-body-paragraph ki kj it kk b kl km ju kn ko kp jx kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated"><strong class="kk iu">异常是程序执行</strong>时出现的错误。当异常发生在运行时，它会寻找一个异常处理程序；如果异常处理程序不存在，那么你的程序会突然停止。如果存在异常处理程序，则执行异常处理程序中的代码。</p><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div class="gh gi mf"><img src="../Images/c051b8d79c39b1bcbd8958ebda783d24.png" data-original-src="https://miro.medium.com/v2/resize:fit:1178/format:webp/1*wrKfaBR1469yWv4cxdMwZQ.png"/></div><figcaption class="ma mb gj gh gi mc md bd b be z dk translated">没有异常处理程序的代码和有异常处理程序的代码</figcaption></figure><p id="97b9" class="pw-post-body-paragraph ki kj it kk b kl km ju kn ko kp jx kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">为了处理异常，我们使用了try、except和finally块。</p><h2 id="beb9" class="mg mh it bd mi mj mk dn ml mm mn dp mo kr mp mq mr kv ms mt mu kz mv mw mx my bi translated"><strong class="ak">异常处理程序</strong>中的Try and Except块</h2><p id="27a4" class="pw-post-body-paragraph ki kj it kk b kl mz ju kn ko na jx kq kr nb kt ku kv nc kx ky kz nd lb lc ld im bi translated">首先，执行try块内的代码；如果没有错误，那么except块将被跳过。</p><p id="20e8" class="pw-post-body-paragraph ki kj it kk b kl km ju kn ko kp jx kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">如果try块中有错误，那么try块中的其余代码将被跳过。控制被传递到except块以处理异常</p><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div class="gh gi ne"><img src="../Images/61e80db50f1894a3287df539b95dacb3.png" data-original-src="https://miro.medium.com/v2/resize:fit:1138/format:webp/1*4oSRwn6Xi6--BAgbnXkp1w.png"/></div></figure><pre class="lt lu lv lw gt nf ng nh ni aw nj bi"><span id="eabd" class="mg mh it ng b gy nk nl l nm nn"><strong class="ng iu">try:</strong><br/>    f= open("a.csv", "r") <br/>    data=f.read()<br/>    print(data)<br/><strong class="ng iu">except:</strong><br/>    print("Some error")</span></pre><p id="1508" class="pw-post-body-paragraph ki kj it kk b kl km ju kn ko kp jx kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">如果文件a.csv存在，那么我们得到文件a.csv的内容</p><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div class="gh gi no"><img src="../Images/17245e85d6113473588051c37fcc25f6.png" data-original-src="https://miro.medium.com/v2/resize:fit:398/format:webp/1*0E8En5F7L53WeUsD9CNKgQ.png"/></div><figcaption class="ma mb gj gh gi mc md bd b be z dk translated">输出，当文件a.csv存在并且代码中没有错误时，将显示文件的内容</figcaption></figure><p id="615c" class="pw-post-body-paragraph ki kj it kk b kl km ju kn ko kp jx kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">如果文件a.csv不存在，那么我们得到消息"<em class="np">有些错误。</em>"来自异常处理程序。</p><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div class="gh gi nq"><img src="../Images/b111ea95b4acc4017b4257a11a6cf1e7.png" data-original-src="https://miro.medium.com/v2/resize:fit:232/format:webp/1*2ENTocSuhKoLzLsdHoE_Eg.png"/></div><figcaption class="ma mb gj gh gi mc md bd b be z dk translated">当文件a.csv不存在时，输出存在</figcaption></figure><h2 id="b056" class="mg mh it bd mi mj mk dn ml mm mn dp mo kr mp mq mr kv ms mt mu kz mv mw mx my bi translated">异常处理程序中的finally块</h2><p id="863a" class="pw-post-body-paragraph ki kj it kk b kl mz ju kn ko na jx kq kr nb kt ku kv nc kx ky kz nd lb lc ld im bi translated">finally块是异常处理程序中的可选子句。它用于任何情况下需要执行的任何清理操作。</p><p id="61c0" class="pw-post-body-paragraph ki kj it kk b kl km ju kn ko kp jx kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">在两种情况下都会执行finally块:成功执行try块中的所有语句，以及在try块执行期间出现异常。</p><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div role="button" tabindex="0" class="ns nt di nu bf nv"><div class="gh gi nr"><img src="../Images/ae8bc551ad5f70a79991e4ba7ee6d7ee.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*VrqGJspo4J7XRN2w003Dow.png"/></div></div></figure><pre class="lt lu lv lw gt nf ng nh ni aw nj bi"><span id="fe88" class="mg mh it ng b gy nk nl l nm nn"><strong class="ng iu">try:</strong><br/>    f= open("a.csv", "r") <br/>    data=f.read()<br/>    print(data)<br/><strong class="ng iu">except:</strong><br/>    print("Some error")<br/><strong class="ng iu">finally:</strong><br/>    print("finally closing the file")<br/>    f.close()</span></pre><p id="b16a" class="pw-post-body-paragraph ki kj it kk b kl km ju kn ko kp jx kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">如果文件a.csv存在，那么我们得到文件a.csv的内容，后跟消息“<em class="np">最终关闭文件</em>”，并关闭finally块中提到的文件</p><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div class="gh gi nw"><img src="../Images/33ded3b4d9bb744bd9d149d973de90c3.png" data-original-src="https://miro.medium.com/v2/resize:fit:540/format:webp/1*MJYrMl0-VTLTLDVL8wYWSg.png"/></div><figcaption class="ma mb gj gh gi mc md bd b be z dk translated">当代码中没有出现异常时，输出</figcaption></figure><p id="77e2" class="pw-post-body-paragraph ki kj it kk b kl km ju kn ko kp jx kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">如果文件a.csv不存在，那么我们得到消息“<em class="np">有些错误</em>”，后跟消息“<em class="np">最终关闭文件</em>”。执行except块和finally块中的代码</p><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div class="gh gi nx"><img src="../Images/7b9b7108cc6f02360debd671186a473c.png" data-original-src="https://miro.medium.com/v2/resize:fit:548/format:webp/1*4ah-QznfvPKujlWgWJyjNg.png"/></div><figcaption class="ma mb gj gh gi mc md bd b be z dk translated">当文件a.csv不存在、存在且发生异常时的输出</figcaption></figure><h2 id="bc3b" class="mg mh it bd mi mj mk dn ml mm mn dp mo kr mp mq mr kv ms mt mu kz mv mw mx my bi translated">异常处理程序的Else块</h2><p id="e77d" class="pw-post-body-paragraph ki kj it kk b kl mz ju kn ko na jx kq kr nb kt ku kv nc kx ky kz nd lb lc ld im bi translated">Else和finally一样也是可选块，但后面必须跟except块。当try块中没有异常发生时，该块在提供的try块之后执行。</p><p id="eb45" class="pw-post-body-paragraph ki kj it kk b kl km ju kn ko kp jx kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">如果try块中存在异常，则不执行该块</p><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div role="button" tabindex="0" class="ns nt di nu bf nv"><div class="gh gi ny"><img src="../Images/4c5234588ce6dbc637ad5c9620463cde.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*K_f7fO0fvKmG0D-Rd7-3bw.png"/></div></div></figure><pre class="lt lu lv lw gt nf ng nh ni aw nj bi"><span id="6576" class="mg mh it ng b gy nk nl l nm nn"><strong class="ng iu">try:</strong><br/>    f= open("b.csv", "r") <br/>    data=f.read()<br/>    print(data)<br/><strong class="ng iu">except:</strong><br/>    print("Some error")<br/><strong class="ng iu">else:</strong><br/>    print("No exception, everything good")    <br/><strong class="ng iu">finally:</strong><br/>    print("finally closing the file")<br/>    f.close()</span></pre><p id="a0e3" class="pw-post-body-paragraph ki kj it kk b kl km ju kn ko kp jx kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">如果文件a.csv存在，那么我们得到文件a.csv的内容，后跟来自else块的消息<em class="np">“无异常，一切正常】，</em>后跟消息<em class="np">“最终关闭文件”</em>，并关闭finally块中提到的文件</p><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div class="gh gi nz"><img src="../Images/d9d8fbbd218d82b5fab72035ab717fd3.png" data-original-src="https://miro.medium.com/v2/resize:fit:668/format:webp/1*NazyWw0NzOfb61zSnwQ0qQ.png"/></div><figcaption class="ma mb gj gh gi mc md bd b be z dk translated">当代码中没有出现异常时，输出</figcaption></figure><p id="180f" class="pw-post-body-paragraph ki kj it kk b kl km ju kn ko kp jx kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">如果文件a.csv不存在，那么我们得到消息“<em class="np">有些错误</em>”，接着是消息“<em class="np">最终关闭文件</em>”。这不会执行else块的代码</p><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div class="gh gi nx"><img src="../Images/7b9b7108cc6f02360debd671186a473c.png" data-original-src="https://miro.medium.com/v2/resize:fit:548/format:webp/1*4ah-QznfvPKujlWgWJyjNg.png"/></div><figcaption class="ma mb gj gh gi mc md bd b be z dk translated">当a.csv文件不存在时，输出存在并发生异常</figcaption></figure><h2 id="623f" class="mg mh it bd mi mj mk dn ml mm mn dp mo kr mp mq mr kv ms mt mu kz mv mw mx my bi translated">处理多个内置异常</h2><p id="7b1e" class="pw-post-body-paragraph ki kj it kk b kl mz ju kn ko na jx kq kr nb kt ku kv nc kx ky kz nd lb lc ld im bi translated">在下一段代码中，您将学习在try-except块中处理多个内置异常。</p><p id="820a" class="pw-post-body-paragraph ki kj it kk b kl km ju kn ko kp jx kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">您将通过在except块中指定不同的内置异常来处理这个问题。在下面的例子中，我们正在处理多个内置异常:找不到文件、文件不存在以及except块中的权限错误</p><p id="d486" class="pw-post-body-paragraph ki kj it kk b kl km ju kn ko kp jx kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">为了处理除内置异常以外的任何其他异常，我们只指定except子句only</p><pre class="lt lu lv lw gt nf ng nh ni aw nj bi"><span id="9add" class="mg mh it ng b gy nk nl l nm nn"><strong class="ng iu">import sys<br/>try:</strong><br/>    f= open("a.csv", "r") <br/>    data=f.read()<br/>    print(data)<br/><strong class="ng iu">except (FileNotFoundError, FileExistsError, PermissionError ) as fnf:</strong><br/>    print(" Buit-in exception",fnf)<br/><strong class="ng iu">except:</strong><br/>    print("Some error in opening and reading file", sys.exc_info())<br/><strong class="ng iu">finally:</strong><br/>    f.close()</span></pre><p id="5ce0" class="pw-post-body-paragraph ki kj it kk b kl km ju kn ko kp jx kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">当文件a.csv不存在时，我们会得到以下消息。对于任何其他错误，我们会得到堆栈跟踪</p><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div role="button" tabindex="0" class="ns nt di nu bf nv"><div class="gh gi oa"><img src="../Images/bcb17461c1330ad0922666f4e6f2480c.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*vjDWEwVwK1f8I7NJCLD8-A.png"/></div></div></figure><h2 id="9504" class="mg mh it bd mi mj mk dn ml mm mn dp mo kr mp mq mr kv ms mt mu kz mv mw mx my bi translated">创建用户定义的异常</h2><p id="6e07" class="pw-post-body-paragraph ki kj it kk b kl mz ju kn ko na jx kq kr nb kt ku kv nc kx ky kz nd lb lc ld im bi translated">为了创建用户定义的异常，我们创建一个直接或间接从<strong class="kk iu">异常</strong>类派生的类，</p><p id="22cd" class="pw-post-body-paragraph ki kj it kk b kl km ju kn ko kp jx kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">在下面的例子中，我们创建了一个从Exception类派生的类MyError</p><pre class="lt lu lv lw gt nf ng nh ni aw nj bi"><span id="11c2" class="mg mh it ng b gy nk nl l nm nn"><strong class="ng iu">class MyError(Exception):<br/>    def __init__(self, col_names):<br/>        self. col_names = col_names<br/>    def getColNames(self):<br/>        return self.col_names</strong></span></pre><p id="6d5d" class="pw-post-body-paragraph ki kj it kk b kl km ju kn ko kp jx kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">引发用户定义的异常的代码</p><pre class="lt lu lv lw gt nf ng nh ni aw nj bi"><span id="420a" class="mg mh it ng b gy nk nl l nm nn"><strong class="ng iu">import pandas as pd<br/>def check_if_column_present(column_name, filename):</strong><br/>    <strong class="ng iu">try:</strong><br/>        data=pd.read_csv(filename)<br/>        if column_name in data.columns:<br/>            return True<br/>        else:<br/>            <strong class="ng iu">raise MyError(data.columns)</strong><br/>   <strong class="ng iu"> except(FileNotFoundError)as fnf:</strong><br/>        print(fnf)<br/>    <strong class="ng iu">except MyError as error:<br/>        print( " My error", error.col_names)</strong><br/>    except:<br/>        print(" error in function ", sys.exc_info())</span><span id="5f63" class="mg mh it ng b gy ob nl l nm nn"><strong class="ng iu">check_if_column_present("a", "a.csv")</strong></span></pre><figure class="lt lu lv lw gt lx gh gi paragraph-image"><div class="gh gi oc"><img src="../Images/7ff9468bc3d0f2f5335dc253cd585c0f.png" data-original-src="https://miro.medium.com/v2/resize:fit:1048/format:webp/1*Y3Wi6BzCFyW65Gy0y4eOEw.png"/></div><figcaption class="ma mb gj gh gi mc md bd b be z dk translated">用户定义的异常消息</figcaption></figure><h2 id="df68" class="mg mh it bd mi mj mk dn ml mm mn dp mo kr mp mq mr kv ms mt mu kz mv mw mx my bi translated">结论:</h2><p id="3f41" class="pw-post-body-paragraph ki kj it kk b kl mz ju kn ko na jx kq kr nb kt ku kv nc kx ky kz nd lb lc ld im bi translated">任何编码语言中的异常处理对于优雅地处理运行时可能发生的异常都很重要。在python中，您可以使用<strong class="kk iu"> try-except -finally，</strong>块来实现。您还可以创建从Exception类派生的用户定义的异常。</p><h2 id="3a11" class="mg mh it bd mi mj mk dn ml mm mn dp mo kr mp mq mr kv ms mt mu kz mv mw mx my bi translated">参考:</h2><p id="e644" class="pw-post-body-paragraph ki kj it kk b kl mz ju kn ko na jx kq kr nb kt ku kv nc kx ky kz nd lb lc ld im bi translated"><a class="ae me" href="https://docs.python.org/3/tutorial/errors.html" rel="noopener ugc nofollow" target="_blank">https://docs.python.org/3/tutorial/errors.html</a></p></div></div>    
</body>
</html>